samples:
  name:
  - Ftt_1
  - Ftt_2
  - Ftt_3
  raw_reads_r1:
  - /home/ruop/Projects/2026_Pipeline_validation/Validation/Francisella_tularensis/raw_reads/Ftt/Ftt_200x_1_R1.fastq
  - /home/ruop/Projects/2026_Pipeline_validation/Validation/Francisella_tularensis/raw_reads/Ftt/Ftt_200x_2_R1.fastq
  - /home/ruop/Projects/2026_Pipeline_validation/Validation/Francisella_tularensis/raw_reads/Ftt/Ftt_200x_3_R1.fastq
  raw_reads_r2:
  - /home/ruop/Projects/2026_Pipeline_validation/Validation/Francisella_tularensis/raw_reads/Ftt/Ftt_200x_1_R2.fastq
  - /home/ruop/Projects/2026_Pipeline_validation/Validation/Francisella_tularensis/raw_reads/Ftt/Ftt_200x_2_R2.fastq
  - /home/ruop/Projects/2026_Pipeline_validation/Validation/Francisella_tularensis/raw_reads/Ftt/Ftt_200x_3_R2.fastq
  species: Francisella tularensis
  genome_size: '1900000'
read_type: illumina-PE
assembly:
  pilon:
    additional_args: --fix all
  minimap2:
    preset: sr
    additional_args: ''
  spades:
    isolate: --isolate
resources:
  general:
    runtime: 18000
    mem_mb: 20000
    cpus: 16
    runtime: 60000
    mem_mb: 40000
    cpus: 24
  checkM:
    runtime: 18000
    mem_mb: 60000
    cpus: 16