samples:
  name:
  - 46W
  raw_reads_r1:
  - /home/ruop/Projects/2026_Burkholderia_ML/raw_reads/46W_R1.fastq
  raw_reads_r2:
  - /home/ruop/Projects/2026_Burkholderia_ML/raw_reads/46W_R2.fastq
  species: Francisella tularensis
  genome_size: '1900000'
read_type: illumina-PE
assembly:
  pilon:
    additional_args: --fix all
  minimap2:
    preset: sr
    additional_args: ''
  spades:
    isolate: --isolate
resources:
  general:
    runtime: 60000
    mem_mb: 40000
    cpus: 24
  checkM:
    runtime: 18000
    mem_mb: 60000
    cpus: 16
